/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pt.pirate_galaxy;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;

/**
 *
 * @author Sergio Cea
 */
public class Conexion extends javax.swing.JFrame {

    Connect conn;
    Connection reg;
    /**
     * Creates new form Connection
     */
    public Conexion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(getIconImage());
        
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Sergio Cea\\Documents\\NetBeansProjects\\pirate_galaxy\\src\\main\\java\\images\\pirategalaxy_skull.png");
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jButtonCon = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        javax.swing.JLabel jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergio Cea\\Documents\\NetBeansProjects\\pirate_galaxy\\src\\main\\java\\images\\pirategalaxy_logo.png"));
        jLabelLogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, 160));

        jButtonCon.setBackground(new java.awt.Color(54, 78, 99));
        jButtonCon.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButtonCon.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCon.setText("Conectar");
        jButtonCon.setBorderPainted(false);
        jButtonCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 100, -1));

        jButtonExit.setBackground(new java.awt.Color(54, 78, 99));
        jButtonExit.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Salir");
        jButtonExit.setBorderPainted(false);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 80, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\\\Users\\\\Sergio Cea\\\\Documents\\\\NetBeansProjects\\\\pirate_galaxy\\\\src\\\\main\\\\java\\\\images\\\\moon02.jpg"));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConActionPerformed
        // TODO add your handling code here:
        conn = new Connect();
        reg = conn.getConnection();
    }//GEN-LAST:event_jButtonConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCon;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
