/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pt.pirate_galaxy;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;

/**
 *
 * @author Sergio Cea
 */
public class Dashboard extends javax.swing.JFrame {

    Connect c ;
    Connection conn;
    //JMenuItem misiones;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(getIconImage());
        //this.setMisionesMenu();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Sergio Cea\\Documents\\NetBeansProjects\\pirate_galaxy\\src\\main\\java\\images\\pirategalaxy_skull.png");
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopDes = new javax.swing.JDesktopPane();
        jMenuOpciones = new javax.swing.JMenuBar();
        jNaves = new javax.swing.JMenu();
        jNavesVega = new javax.swing.JMenuItem();
        jNavesAntares = new javax.swing.JMenuItem();
        jNavesGemini = new javax.swing.JMenuItem();
        jNavesMizar = new javax.swing.JMenuItem();
        jNavesSol = new javax.swing.JMenuItem();
        jNavesDraconis = new javax.swing.JMenuItem();
        jNavesSirius = new javax.swing.JMenuItem();
        jNavesTauCeti = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuAzules = new javax.swing.JMenu();
        jAzulesVega = new javax.swing.JMenuItem();
        jAzulesAntares = new javax.swing.JMenuItem();
        jAzulesGemini = new javax.swing.JMenuItem();
        jAzulesMizar = new javax.swing.JMenuItem();
        jAzulesSol = new javax.swing.JMenuItem();
        jAzulesDraconis = new javax.swing.JMenuItem();
        jMenuDorados = new javax.swing.JMenu();
        jDoradoVega = new javax.swing.JMenuItem();
        jDoradoAntares = new javax.swing.JMenuItem();
        jDoradoGemini = new javax.swing.JMenuItem();
        jDoradoMizar = new javax.swing.JMenuItem();
        jDoradoSol = new javax.swing.JMenuItem();
        jDoradoDraconis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opciones");
        setExtendedState(6);
        setName("Opciones"); // NOI18N

        javax.swing.GroupLayout jDesktopDesLayout = new javax.swing.GroupLayout(jDesktopDes);
        jDesktopDes.setLayout(jDesktopDesLayout);
        jDesktopDesLayout.setHorizontalGroup(
            jDesktopDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jDesktopDesLayout.setVerticalGroup(
            jDesktopDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jNaves.setText("Naves");
        jNaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesActionPerformed(evt);
            }
        });

        jNavesVega.setText("Vega");
        jNavesVega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesVegaActionPerformed(evt);
            }
        });
        jNaves.add(jNavesVega);

        jNavesAntares.setText("Antares");
        jNavesAntares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesAntaresActionPerformed(evt);
            }
        });
        jNaves.add(jNavesAntares);

        jNavesGemini.setText("Gemini");
        jNavesGemini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesGeminiActionPerformed(evt);
            }
        });
        jNaves.add(jNavesGemini);

        jNavesMizar.setText("Mizar");
        jNavesMizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesMizarActionPerformed(evt);
            }
        });
        jNaves.add(jNavesMizar);

        jNavesSol.setText("Sol");
        jNavesSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesSolActionPerformed(evt);
            }
        });
        jNaves.add(jNavesSol);

        jNavesDraconis.setText("Draconis");
        jNavesDraconis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesDraconisActionPerformed(evt);
            }
        });
        jNaves.add(jNavesDraconis);

        jNavesSirius.setText("Sirius");
        jNavesSirius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesSiriusActionPerformed(evt);
            }
        });
        jNaves.add(jNavesSirius);

        jNavesTauCeti.setText("Tau Ceti");
        jNavesTauCeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesTauCetiActionPerformed(evt);
            }
        });
        jNaves.add(jNavesTauCeti);

        jMenuOpciones.add(jNaves);

        jMenu1.setText("Planos");

        jMenuAzules.setText("Azules");

        jAzulesVega.setText("Vega");
        jAzulesVega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAzulesVegaActionPerformed(evt);
            }
        });
        jMenuAzules.add(jAzulesVega);

        jAzulesAntares.setText("Antares");
        jAzulesAntares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAzulesAntaresActionPerformed(evt);
            }
        });
        jMenuAzules.add(jAzulesAntares);

        jAzulesGemini.setText("Gemini");
        jAzulesGemini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAzulesGeminiActionPerformed(evt);
            }
        });
        jMenuAzules.add(jAzulesGemini);

        jAzulesMizar.setText("Mizar");
        jAzulesMizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAzulesMizarActionPerformed(evt);
            }
        });
        jMenuAzules.add(jAzulesMizar);

        jAzulesSol.setText("Sol");
        jAzulesSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAzulesSolActionPerformed(evt);
            }
        });
        jMenuAzules.add(jAzulesSol);

        jAzulesDraconis.setText("Draconis");
        jAzulesDraconis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAzulesDraconisActionPerformed(evt);
            }
        });
        jMenuAzules.add(jAzulesDraconis);

        jMenu1.add(jMenuAzules);

        jMenuDorados.setText("Dorados");

        jDoradoVega.setText("Vega");
        jDoradoVega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoradoVegaActionPerformed(evt);
            }
        });
        jMenuDorados.add(jDoradoVega);

        jDoradoAntares.setText("Antares");
        jDoradoAntares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoradoAntaresActionPerformed(evt);
            }
        });
        jMenuDorados.add(jDoradoAntares);

        jDoradoGemini.setText("Gemini");
        jDoradoGemini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoradoGeminiActionPerformed(evt);
            }
        });
        jMenuDorados.add(jDoradoGemini);

        jDoradoMizar.setText("Mizar");
        jDoradoMizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoradoMizarActionPerformed(evt);
            }
        });
        jMenuDorados.add(jDoradoMizar);

        jDoradoSol.setText("Sol");
        jDoradoSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoradoSolActionPerformed(evt);
            }
        });
        jMenuDorados.add(jDoradoSol);

        jDoradoDraconis.setText("Draconis");
        jDoradoDraconis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoradoDraconisActionPerformed(evt);
            }
        });
        jMenuDorados.add(jDoradoDraconis);

        jMenu1.add(jMenuDorados);

        jMenuOpciones.add(jMenu1);

        setJMenuBar(jMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopDes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopDes)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Error de redundancia en la variable misiones
    /*private void setMisionesMenu () {
        c = new Connect ();
        conn = c.getConnection();
                          
        try {
            Statement stm = conn.createStatement();
            ResultSet counter = stm.executeQuery("SELECT * FROM `sistemas`");

            int count = 0;
            while(counter.next()){count++;}
            
            
            ResultSet se = stm.executeQuery("SELECT * FROM `sistemas`");
            

            while(se.next()){
                misiones = new javax.swing.JMenuItem();
                misiones.setText(se.getString("nombre"));
                misiones.addActionListener(this::jMisionesActionPerformed);
                Misiones.add(misiones);
            }
            
        }catch (SQLException e){
            System.out.println("ERROR");
        }
    }*/
    
   
    //Naves
    private void jNavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jNavesActionPerformed

    private void jNavesVegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesVegaActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesVega.getText();
        Naves navVega = null;
        try {
            navVega = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(navVega);
        navVega.show();
    }//GEN-LAST:event_jNavesVegaActionPerformed

    private void jNavesAntaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesAntaresActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesAntares.getText();
        Naves antares = null;
        try {
            antares = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(antares);
        antares.show();
    }//GEN-LAST:event_jNavesAntaresActionPerformed

    private void jNavesGeminiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesGeminiActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesAntares.getText();
        Naves gemini = null;
        try {
            gemini = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(gemini);
        gemini.show();
    }//GEN-LAST:event_jNavesGeminiActionPerformed

    private void jNavesMizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesMizarActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesMizar.getText();
        Naves mizar = null;
        try {
            mizar = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(mizar);
        mizar.show();
    }//GEN-LAST:event_jNavesMizarActionPerformed

    private void jNavesSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesSolActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesSol.getText();
        Naves sol = null;
        try {
            sol = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(sol);
        sol.show();
    }//GEN-LAST:event_jNavesSolActionPerformed

    private void jNavesDraconisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesDraconisActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesDraconis.getText();
        Naves draco = null;
        try {
            draco = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(draco);
        draco.show();
    }//GEN-LAST:event_jNavesDraconisActionPerformed

    private void jNavesSiriusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesSiriusActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesSirius.getText();
        Naves sirius = null;
        try {
            sirius = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(sirius);
        sirius.show();
    }//GEN-LAST:event_jNavesSiriusActionPerformed

    private void jNavesTauCetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesTauCetiActionPerformed
        // TODO add your handling code here:
        String sistema = jNavesTauCeti.getText();
        Naves tau = null;
        try {
            tau = new Naves(sistema);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopDes.add(tau);
        tau.show();
    }//GEN-LAST:event_jNavesTauCetiActionPerformed

    //Planos Draconis
    private void jAzulesDraconisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAzulesDraconisActionPerformed
        // TODO add your handling code here:
        String sistema = jAzulesDraconis.getText();
        String tipo;
        Planos draconis;
        if (jMenuAzules.getText().equalsIgnoreCase("Azules")) {
            tipo = "Azul";
            draconis = new Planos(sistema, tipo);
            jDesktopDes.add(draconis);
            draconis.show();
        }
    }//GEN-LAST:event_jAzulesDraconisActionPerformed

    private void jDoradoDraconisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoradoDraconisActionPerformed
        // TODO add your handling code here:
        String sistema = jDoradoDraconis.getText();
        String tipo;
        Planos draconis;
        if (jMenuDorados.getText().equalsIgnoreCase("Dorados")) {
            tipo = "Dorado";
            draconis = new Planos(sistema, tipo);
            jDesktopDes.add(draconis);
            draconis.show();
        }
    }//GEN-LAST:event_jDoradoDraconisActionPerformed

    //Planos Azules
    private void jAzulesVegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAzulesVegaActionPerformed
        // TODO add your handling code here:
        String sistema = jAzulesVega.getText();
        String tipo;
        Planos vega;
        if (jMenuAzules.getText().equalsIgnoreCase("Azules")) {
            tipo = "Azul";
            vega = new Planos(sistema, tipo);
            jDesktopDes.add(vega);
            vega.show();
        }
    
    }//GEN-LAST:event_jAzulesVegaActionPerformed

    private void jAzulesAntaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAzulesAntaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAzulesAntaresActionPerformed

    private void jAzulesGeminiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAzulesGeminiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAzulesGeminiActionPerformed

    private void jAzulesMizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAzulesMizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAzulesMizarActionPerformed

    private void jAzulesSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAzulesSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAzulesSolActionPerformed

    //Planso Dorados
    private void jDoradoVegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoradoVegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoradoVegaActionPerformed

    private void jDoradoAntaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoradoAntaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoradoAntaresActionPerformed

    private void jDoradoGeminiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoradoGeminiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoradoGeminiActionPerformed

    private void jDoradoMizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoradoMizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoradoMizarActionPerformed

    private void jDoradoSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoradoSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoradoSolActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAzulesAntares;
    private javax.swing.JMenuItem jAzulesDraconis;
    private javax.swing.JMenuItem jAzulesGemini;
    private javax.swing.JMenuItem jAzulesMizar;
    private javax.swing.JMenuItem jAzulesSol;
    private javax.swing.JMenuItem jAzulesVega;
    private javax.swing.JDesktopPane jDesktopDes;
    private javax.swing.JMenuItem jDoradoAntares;
    private javax.swing.JMenuItem jDoradoDraconis;
    private javax.swing.JMenuItem jDoradoGemini;
    private javax.swing.JMenuItem jDoradoMizar;
    private javax.swing.JMenuItem jDoradoSol;
    private javax.swing.JMenuItem jDoradoVega;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAzules;
    private javax.swing.JMenu jMenuDorados;
    private javax.swing.JMenuBar jMenuOpciones;
    private javax.swing.JMenu jNaves;
    private javax.swing.JMenuItem jNavesAntares;
    private javax.swing.JMenuItem jNavesDraconis;
    private javax.swing.JMenuItem jNavesGemini;
    private javax.swing.JMenuItem jNavesMizar;
    private javax.swing.JMenuItem jNavesSirius;
    private javax.swing.JMenuItem jNavesSol;
    private javax.swing.JMenuItem jNavesTauCeti;
    private javax.swing.JMenuItem jNavesVega;
    // End of variables declaration//GEN-END:variables
}
