/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pt.pirate_galaxy;

/**
 *
 * @author Sergio Cea
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopDes = new javax.swing.JDesktopPane();
        jMenuOpciones = new javax.swing.JMenuBar();
        jNaves = new javax.swing.JMenu();
        jNavesVega = new javax.swing.JMenuItem();
        jNavesAntares = new javax.swing.JMenuItem();
        jNavesGemini = new javax.swing.JMenuItem();
        jNavesMizar = new javax.swing.JMenuItem();
        jNavesSol = new javax.swing.JMenuItem();
        jNavesDraconis = new javax.swing.JMenuItem();
        jNavesSirius = new javax.swing.JMenuItem();
        jNavesTauCeti = new javax.swing.JMenuItem();
        jPlanos = new javax.swing.JMenu();
        jPlanosVega = new javax.swing.JMenuItem();
        jPlanosAntares = new javax.swing.JMenuItem();
        jPlanosGemini = new javax.swing.JMenuItem();
        jPlanosMizar = new javax.swing.JMenuItem();
        jPlanosSol = new javax.swing.JMenuItem();
        jPlanosDraconis = new javax.swing.JMenuItem();
        jPlanosTauCeti = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opciones");
        setExtendedState(6);
        setName("Opciones"); // NOI18N

        javax.swing.GroupLayout jDesktopDesLayout = new javax.swing.GroupLayout(jDesktopDes);
        jDesktopDes.setLayout(jDesktopDesLayout);
        jDesktopDesLayout.setHorizontalGroup(
            jDesktopDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jDesktopDesLayout.setVerticalGroup(
            jDesktopDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jNaves.setText("Naves");
        jNaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesActionPerformed(evt);
            }
        });

        jNavesVega.setText("Vega");
        jNavesVega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesVegaActionPerformed(evt);
            }
        });
        jNaves.add(jNavesVega);

        jNavesAntares.setText("Antares");
        jNavesAntares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNavesAntaresActionPerformed(evt);
            }
        });
        jNaves.add(jNavesAntares);

        jNavesGemini.setText("Gemini");
        jNaves.add(jNavesGemini);

        jNavesMizar.setText("Mizar");
        jNaves.add(jNavesMizar);

        jNavesSol.setText("Sol");
        jNaves.add(jNavesSol);

        jNavesDraconis.setText("Draconis");
        jNaves.add(jNavesDraconis);

        jNavesSirius.setText("Sirius");
        jNaves.add(jNavesSirius);

        jNavesTauCeti.setText("Tau Ceti");
        jNaves.add(jNavesTauCeti);

        jMenuOpciones.add(jNaves);

        jPlanos.setText("Planos");
        jPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlanosActionPerformed(evt);
            }
        });

        jPlanosVega.setText("Vega");
        jPlanosVega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlanosVegaActionPerformed(evt);
            }
        });
        jPlanos.add(jPlanosVega);

        jPlanosAntares.setText("Antares");
        jPlanosAntares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlanosAntaresActionPerformed(evt);
            }
        });
        jPlanos.add(jPlanosAntares);

        jPlanosGemini.setText("Gemini");
        jPlanos.add(jPlanosGemini);

        jPlanosMizar.setText("Mizar");
        jPlanos.add(jPlanosMizar);

        jPlanosSol.setText("Sol");
        jPlanos.add(jPlanosSol);

        jPlanosDraconis.setText("Draconis");
        jPlanos.add(jPlanosDraconis);

        jPlanosTauCeti.setText("Sirius");
        jPlanos.add(jPlanosTauCeti);

        jMenuOpciones.add(jPlanos);

        setJMenuBar(jMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopDes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopDes)
        );

        getAccessibleContext().setAccessibleName("Opciones");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jNavesActionPerformed

    private void jNavesVegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesVegaActionPerformed
        // TODO add your handling code here:
         NavesVega navVega = new NavesVega();
        jDesktopDes.add(navVega);
        navVega.show();
    }//GEN-LAST:event_jNavesVegaActionPerformed

    private void jNavesAntaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNavesAntaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNavesAntaresActionPerformed

    private void jPlanosVegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlanosVegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlanosVegaActionPerformed

    private void jPlanosAntaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlanosAntaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlanosAntaresActionPerformed

    private void jPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlanosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopDes;
    private javax.swing.JMenuBar jMenuOpciones;
    private javax.swing.JMenu jNaves;
    private javax.swing.JMenuItem jNavesAntares;
    private javax.swing.JMenuItem jNavesDraconis;
    private javax.swing.JMenuItem jNavesGemini;
    private javax.swing.JMenuItem jNavesMizar;
    private javax.swing.JMenuItem jNavesSirius;
    private javax.swing.JMenuItem jNavesSol;
    private javax.swing.JMenuItem jNavesTauCeti;
    private javax.swing.JMenuItem jNavesVega;
    private javax.swing.JMenu jPlanos;
    private javax.swing.JMenuItem jPlanosAntares;
    private javax.swing.JMenuItem jPlanosDraconis;
    private javax.swing.JMenuItem jPlanosGemini;
    private javax.swing.JMenuItem jPlanosMizar;
    private javax.swing.JMenuItem jPlanosSol;
    private javax.swing.JMenuItem jPlanosTauCeti;
    private javax.swing.JMenuItem jPlanosVega;
    // End of variables declaration//GEN-END:variables
}
